### PR TITLE
multiple fixes

### PR DESCRIPTION
**Pull request by Procyon-b**
fix for:
- incognito mode cookies
- cookie with no name now editable
- support for range selection
- domain name max-length css only
- cookie name max-length css only
- save/restore list sorting fixed
- filters input fields: only letters are taken into account
- background page settings were not updated (restart was needed)
- hide error message when a specific cookie restore is refused ("non-secure" cookie restored over a "secure" cookie)

### CODE REVIEW

**Comment by Procyon-b** [comment]
I have it running since sunday, in place of the minified version, without any new problem.
If you have questions...

Can I ask what program/script you use to minify your code?
I have tried comparing another extension between its original code and a fork (I don't know what that guy is up to). But, even if I have found some changes, I must have missed some. And I still have a couple of files to check.
I have tried minifying the original code to try to match it with the copy, but have not found a minifier that uses the same technique.

**Comment by Phatsuo** [comment]
@Procyon-b Thanks a bunch! After testing this I will release it... hopefully in the next week.

I use the closure compiler https://github.com/google/closure-compiler, although it is an older compiled version that I have not updated in a while, then I run another script I wrote that minimizes the function names that closure compiler does not touch.

**Comment by Phatsuo** [comment]
@Procyon-b Running it locally w/ a few more changes. Assuming I hit no problems, I should be able to have this released Sunday. =)

**Comment by Phatsuo** [comment]
@Procyon-b Published!

**Comment by Procyon-b** [comment]
Great  :)

but:
Error in response to cookies.getAll: TypeError: $(...).shiftSelectable is not a function
    at Object.callback (chrome-extension://hcpidejphgpcgfnpiehkcckkkemgneif/master.js:16:377)
    at Object.callback (chrome-extension://hcpidejphgpcgfnpiehkcckkkemgneif/master.js:14:233)

Edit:
In fact multis.js is missing

**Comment by Phatsuo** [comment]
Will get this fixed today.

**Comment by Phatsuo** [comment]
@Procyon-b Published.

**Pull request merged**
